USE [master]


/****** Object:  Database [BD1-2020-CEMEPRIAR]    Script Date: 30/03/20 22:14:45 ******/
CREATE DATABASE [BD1-2020-CEMEPRIAR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD1-2020-CEMEPRIAR', FILENAME = N'C:\SQLData\BD1-2020-CEMEPRIAR\BD1-2020-CEMEPRIAR.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BD1-2020-CEMEPRIAR_log', FILENAME = N'C:\SQLData\BD1-2020-CEMEPRIAR\BD1-2020-CEMEPRIAR_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)

ALTER DATABASE [BD1-2020-CEMEPRIAR] SET COMPATIBILITY_LEVEL = 110

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD1-2020-CEMEPRIAR].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [BD1-2020-CEMEPRIAR] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [BD1-2020-CEMEPRIAR] SET ANSI_NULLS OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET ANSI_PADDING OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET ANSI_WARNINGS OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET ARITHABORT OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET AUTO_CLOSE OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET AUTO_SHRINK OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET  DISABLE_BROKER 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET TRUSTWORTHY OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET READ_COMMITTED_SNAPSHOT OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET HONOR_BROKER_PRIORITY OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET RECOVERY SIMPLE 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET  MULTI_USER 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET DB_CHAINING OFF 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET TARGET_RECOVERY_TIME = 0 SECONDS 
USE [BD1-2020-CEMEPRIAR]

/****** Object:  Table [dbo].[Concepto]    Script Date: 30/03/20 22:14:45 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Concepto](
	[idConcepto] [int] NOT NULL,
	[descripcion] [varchar](20) NOT NULL
) ON [PRIMARY]

/****** Object:  Table [dbo].[Especialidad]    Script Date: 30/03/20 22:14:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Especialidad](
	[idEspecialidad] [int] NOT NULL,
	[especialidad] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Especialidad] PRIMARY KEY CLUSTERED 
(
	[idEspecialidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[Historia]    Script Date: 30/03/20 22:14:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Historia](
	[idHistoria] [int] NOT NULL,
	[fechaHistoria] [date] NOT NULL,
	[observacion] [varchar](max) NULL,
	[fechaAlta] [date] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

/****** Object:  Table [dbo].[Medico]    Script Date: 30/03/20 22:14:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Medico](
	[idMedico] [int] NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[apellido] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Medico] PRIMARY KEY CLUSTERED 
(
	[idMedico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[MedicoEspecialidad]    Script Date: 30/03/20 22:14:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MedicoEspecialidad](
	[idMedico] [int] NOT NULL,
	[idEspecialidad] [int] NOT NULL,
	[descripcion] [varchar](50) NULL
) ON [PRIMARY]

/****** Object:  Table [dbo].[Paciente]    Script Date: 30/03/20 22:14:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Paciente](
	[idPaciente] [int] NOT NULL,
	[nombre] [varchar](50) NULL,
	[apellido] [varchar](50) NULL,
	[fNacimiento] [date] NULL,
	[domicilio] [varchar](100) NULL,
	[idPais] [int] NULL,
	[telefono] [varchar](15) NULL,
	[email] [varchar](50) NULL,
	[observacion] [varchar](50) NULL,
	[fechaAlta] [date] NULL,
 CONSTRAINT [PK_paciente] PRIMARY KEY CLUSTERED 
(
	[idPaciente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[Pago]    Script Date: 30/03/20 22:14:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Pago](
	[idPago] [int] NOT NULL,
	[concepto] [varchar](20) NOT NULL,
	[fecha] [date] NOT NULL,
	[monto] [money] NOT NULL,
	[estado] [varchar](10) NOT NULL,
	[obs] [varchar](50) NULL
) ON [PRIMARY]

/****** Object:  Table [dbo].[PagoPaciente]    Script Date: 30/03/20 22:14:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PagoPaciente](
	[idPago] [int] NOT NULL,
	[idPaciente] [int] NOT NULL,
	[idTurno] [int] NOT NULL,
 CONSTRAINT [PK_PagoPaciente] PRIMARY KEY CLUSTERED 
(
	[idPago] ASC,
	[idPaciente] ASC,
	[idTurno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[Pais]    Script Date: 30/03/20 22:14:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Pais](
	[idPais] [int] NOT NULL,
	[pais] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Pais] PRIMARY KEY CLUSTERED 
(
	[idPais] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[Turno]    Script Date: 30/03/20 22:14:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Turno](
	[idTurno] [int] NOT NULL,
	[fechaTurno] [date] NOT NULL,
	[estado] [varchar](10) NOT NULL,
	[observacion] [varchar](50) NULL
) ON [PRIMARY]

/****** Object:  Table [dbo].[TurnoEstado]    Script Date: 30/03/20 22:14:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TurnoEstado](
	[idEstado] [int] NOT NULL,
	[descripcion] [varchar](30) NULL
) ON [PRIMARY]

/****** Object:  Table [dbo].[TurnoPaciente]    Script Date: 30/03/20 22:14:46 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TurnoPaciente](
	[idTurno] [int] NOT NULL,
	[idPaciente] [int] NOT NULL,
	[idMedico] [int] NOT NULL,
 CONSTRAINT [PK_TurnoPaciente] PRIMARY KEY CLUSTERED 
(
	[idTurno] ASC,
	[idPaciente] ASC,
	[idMedico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
USE [master]
ALTER DATABASE [BD1-2020-CEMEPRIAR] SET  READ_WRITE;
